# Interact with the AI Agent Workflow through running the query_sql_agents function.
#
# The query_sql_agents function has the following parameters and returns:
# Parameters:
#     1. input_agent(Agno.Agent): The agent responsible for building the SQL queries.
#     2. output_agent(Agno.Agent): The agent responsible for executing the SQL queries and processing the output.
#     3. max_number_attempts (int): The maximum number of attempts to run the agents. Default is 3.
#     4. print_response (bool): Whether to print the queries and responses. Default is False.
#     5. print_progress (bool): Whether to print the messages outlining the progress of the agents. Default is False.
#
# Returns:
#     1. results(list(dict)): A list of results from the sql_output_agent where each query result is a list element 
#        in the form of the sql_output_agent_response dictionary.
#           -user_query: The user's natural language question.
#           -sql_query: The SQL query generated by sql_input_agent.
#           -response_text: A human-readable summary of the SQL query results or an explanation of an error.
#           -error: A boolean value indicating if an error occurred when executing the query.
#
# The workflow utilises two Agno Agentic AI Agents. These are:
#   1. sql_input_agent: This agent is responsible for processing the input queries and generating the SQL queries.
#   2. sql_output_agent: This agent is responsible for generating the SQL queries and processing the output.
#
# The databse which the sql_input_agent and sql_output_agent use has one table with the following schema.
#   "name": VARCHAR,
#   "country": VARCHAR,
#   'continent': VARCHAR,
#   "downhill_distance_km": FLOAT,
#   "nordic_distance_km": FLOAT,
#   "vertical_m": FLOAT,
#   "min_elevation_m": FLOAT,
#   "max_elevation_m": FLOAT,
#   "lift_count": INTEGER}

from source.hybrid_rag_agents import sql_input_agent, sql_output_agent
from source.query_agents import query_sql_agents

practice_queries = ['What is the elevation of breckenridge?',
                    'What is the average number of chairlifts at ski resorts in Canada?',
                    'What ski resort in Italy has the largest elevation range?',
                    'How many ski resorts are in France and the United States?',]

responses = query_sql_agents(queries=practice_queries,
                             input_agent=sql_input_agent,
                             output_agent=sql_output_agent,
                             max_number_attempts=3,
                             print_response=True,
                             print_progess=True)

print(responses)