from pydantic import BaseModel

class sql_input_agent_response_model(BaseModel):
    """
    Class outlining the response for the sql_input_agent.
    This class defines the structure of the expressions the AI 
    agent will generate for each keyword in the sql query.

    It includes:
    - SELECT: The columns to select in the SQL query.
    - FROM: The table to select from in the SQL query.
    - WHERE: The conditions to filter the results in the SQL query.
    - HAVING: The conditions to filter the results after aggregation in the SQL query.
    - GROUPBY: The columns to group the results by in the SQL query.
    - ORDERBY: The columns to order the results by in the SQL query.
    - LIMIT: The maximum number of results to return in the SQL query.
    """
    SELECT: str
    FROM: str
    WHERE: str
    HAVING: str
    GROUPBY: str
    ORDERBY: str
    LIMIT: str

class sql_output_agent_response_model(BaseModel):
    """
    This class defines the structure of the response from the sql_output_agent.

    It inclides:
    - sql_query: The SQL query generated by the sql_input_agent.
    - response: The human-readable summary of the SQL query results or if there is an error, an explanation of the error.
    - attempts: The number of attempts the agent made to generate a response.
    - error: A boolean indicating if an error occurred during the process.
    """
    user_query: str
    sql_query: str
    response_text: str
    error:bool